### ISSUE TITLE
Reproducing paper's results

### ISSUE THREAD

**Issue by pcardenasg** [bowang-lab/BLEEP#1]
Hello, thanks for sharing your work.

I am currently trying to reproduce your results but haven't been able to find the entire dataset you used and there is also no documentation on how you arrange the dataset for proper processing. Also, there is no specification regarding the required packages. Hence, is it possible for you to please share a set of instructions to correctly reproduce your work? 

Thanks!

**Comment by Xrioen** [comment]
Sorry for the delay. This work was based on data associated with unpublished work at the time. That dataset is now released which allowed me to add the preprocessing script along with various processed outputs. Please let me know if you run into any other issues.
