### ISSUE TITLE
About  the reproducibility

### ISSUE THREAD

**Issue by henryccl** [bowang-lab/BLEEP#7]
Thank you for open-sourcing this interesting work, I am trying to reproduce the results mentioned in the paper, specifically, I am using a 4090 gpu to train the model, I set the batchsize to 256, and all other parameters are used by default. My results from running BLEEP_inference.ipynb with the trained model are as follows, the hvg and mg obtained are even negative, why is this the case and can the author open source the checkpoints?

`Building loaders
Finished loading all files
Finished loading all files
Finished loading all files
Finished loading all files
Finished building loaders
Finished loading model
100%|██████████| 290/290 [00:08<00:00, 34.78it/s]
Building loaders
Finished loading all files
Finished loading all files
Finished loading all files
Finished loading all files
Finished building loaders
  0%|          | 0/290 [00:00<?, ?it/s]Finished loading model
100%|██████████| 290/290 [00:07<00:00, 38.64it/s]
(9269, 256)
(9269, 256)
(2378, 256)
(2378, 256)
(2349, 256)
(2349, 256)
(2277, 256)
(2277, 256)
(2265, 256)
(2265, 256)

image query shape:  (2277, 256)
expression_gt shape:  (2277, 3467)
spot_key shape:  (6992, 256)
expression_key shape:  (6992, 3467)
finding matches, using average of top 50 expressions
torch.Size([2277, 6992])
matched spot embeddings pred shape:  (2277, 256)
matched spot expression pred shape:  (2277, 3467)
(2277, 3467)
(2277, 3467)

Mean correlation across cells:  0.7978978720733318
number of non-zero genes:  3467
max correlation:  0.23411531692744628
mean correlation highly expressed genes:  0.005858165903247573
mean correlation highly variable genes:  -0.012843590028633467

mean correlation marker genes:  -0.04743001734357476
(3467, 2277)
(3467, 2277)`

**Comment by wq2581** [comment]
I have the same issue.

Mean correlation across cells:  0.8019596690894127
number of non-zero genes:  3467
max correlation:  0.5790064845037544
mean correlation highly expressed genes:  -0.008542352918207631
mean correlation highly variable genes:  0.007238810597933147
mean correlation marker genes:  -0.013030684962897124

**Comment by wq2581** [comment]
I have fixed it. Just change the bs and lr.

**Comment by henryccl** [comment]
Correct, the issue has been resolved.
