### ISSUE TITLE
Some questions about the experimental environment setup.

### ISSUE THREAD

**Issue by DaIGaN2019** [bowang-lab/BLEEP#8]
Dear Author:
         Thank you for sharing your code. I'm attempting to reproduce BLEEP but have encountered some issues:
         1. I set the batch size to 512 as described in the paper and used two 2GPU nodes (Tesla V100S GPU, 32GB VRAM) in the SLURM system, but it resulted in a CUDA OUT OF MEMORY error. May I know how much VRAM your GPUs had?
         2. To run the code, I'm facing two options: maintaining the batch size and attempting to use 8 GPUs for reproduction, or reducing the batch size (e.g., to 256). Which option do you think would more closely replicate the results in the paper?
         Thank you for your help!

**Comment by Xrioen** [comment]
Hi, we use a batch size of 128 each, distributed across 4 V100 GPUs (batch size = 512 total), although larger effective batch sizes could potentially produce better results. Of note the results of the paper are produced by computing loss with a batch size of 128 separately on each GPU and only reducing the loss, which may be a bit different than a single loss computed on one batch of 512 examples.
